package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

/**
 * CourseMissionRol generated by hbm2java
 */
public class CourseMissionRol implements java.io.Serializable {

	private int idCourseMissionRol;
	private CourseMission courseMission;
	private Rol rol;

	public CourseMissionRol() {
	}

	public CourseMissionRol(int idCourseMissionRol) {
		this.idCourseMissionRol = idCourseMissionRol;
	}

	public CourseMissionRol(int idCourseMissionRol, CourseMission courseMission, Rol rol) {
		this.idCourseMissionRol = idCourseMissionRol;
		this.courseMission = courseMission;
		this.rol = rol;
	}

	public int getIdCourseMissionRol() {
		return this.idCourseMissionRol;
	}

	public void setIdCourseMissionRol(int idCourseMissionRol) {
		this.idCourseMissionRol = idCourseMissionRol;
	}

	public CourseMission getCourseMission() {
		return this.courseMission;
	}

	public void setCourseMission(CourseMission courseMission) {
		this.courseMission = courseMission;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
