package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CourseMission generated by hbm2java
 */
public class CourseMission implements java.io.Serializable {

	private int idCourseMission;
	private Course course;
	private Mission mission;
	private Note note;
	private Set<CourseMissionRol> courseMissionRols = new HashSet<CourseMissionRol>(0);
	private Set<CourseMissionStudent> courseMissionStudents = new HashSet<CourseMissionStudent>(0);

	public CourseMission() {
	}

	public CourseMission(int idCourseMission) {
		this.idCourseMission = idCourseMission;
	}

	public CourseMission(int idCourseMission, Course course, Mission mission, Note note,
			Set<CourseMissionRol> courseMissionRols, Set<CourseMissionStudent> courseMissionStudents) {
		this.idCourseMission = idCourseMission;
		this.course = course;
		this.mission = mission;
		this.note = note;
		this.courseMissionRols = courseMissionRols;
		this.courseMissionStudents = courseMissionStudents;
	}

	public int getIdCourseMission() {
		return this.idCourseMission;
	}

	public void setIdCourseMission(int idCourseMission) {
		this.idCourseMission = idCourseMission;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	public Note getNote() {
		return this.note;
	}

	public void setNote(Note note) {
		this.note = note;
	}

	public Set<CourseMissionRol> getCourseMissionRols() {
		return this.courseMissionRols;
	}

	public void setCourseMissionRols(Set<CourseMissionRol> courseMissionRols) {
		this.courseMissionRols = courseMissionRols;
	}

	public Set<CourseMissionStudent> getCourseMissionStudents() {
		return this.courseMissionStudents;
	}

	public void setCourseMissionStudents(Set<CourseMissionStudent> courseMissionStudents) {
		this.courseMissionStudents = courseMissionStudents;
	}

}
