package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

/**
 * CourseMissionRolStudent generated by hbm2java
 */
public class CourseMissionRolStudent implements java.io.Serializable {

	private int idCouseMissionRolStudent;
	private Mission mission;
	private RolStudent rolStudent;
	private Integer scoreRolStudent;

	public CourseMissionRolStudent() {
	}

	public CourseMissionRolStudent(int idCouseMissionRolStudent) {
		this.idCouseMissionRolStudent = idCouseMissionRolStudent;
	}

	public CourseMissionRolStudent(int idCouseMissionRolStudent, Mission mission, RolStudent rolStudent,
			Integer scoreRolStudent) {
		this.idCouseMissionRolStudent = idCouseMissionRolStudent;
		this.mission = mission;
		this.rolStudent = rolStudent;
		this.scoreRolStudent = scoreRolStudent;
	}

	public int getIdCouseMissionRolStudent() {
		return this.idCouseMissionRolStudent;
	}

	public void setIdCouseMissionRolStudent(int idCouseMissionRolStudent) {
		this.idCouseMissionRolStudent = idCouseMissionRolStudent;
	}

	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	public RolStudent getRolStudent() {
		return this.rolStudent;
	}

	public void setRolStudent(RolStudent rolStudent) {
		this.rolStudent = rolStudent;
	}

	public Integer getScoreRolStudent() {
		return this.scoreRolStudent;
	}

	public void setScoreRolStudent(Integer scoreRolStudent) {
		this.scoreRolStudent = scoreRolStudent;
	}

}
