package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

/**
 * CourseLanguage generated by hbm2java
 */
public class CourseLanguage implements java.io.Serializable {

	private int idCoruseLanguage;
	private Course course;
	private Language language;
	private Integer progressbarCourseLanguage;
	private String imgCourseLanguage;

	public CourseLanguage() {
	}

	public CourseLanguage(int idCoruseLanguage) {
		this.idCoruseLanguage = idCoruseLanguage;
	}

	public CourseLanguage(int idCoruseLanguage, Course course, Language language, Integer progressbarCourseLanguage,
			String imgCourseLanguage) {
		this.idCoruseLanguage = idCoruseLanguage;
		this.course = course;
		this.language = language;
		this.progressbarCourseLanguage = progressbarCourseLanguage;
		this.imgCourseLanguage = imgCourseLanguage;
	}

	public int getIdCoruseLanguage() {
		return this.idCoruseLanguage;
	}

	public void setIdCoruseLanguage(int idCoruseLanguage) {
		this.idCoruseLanguage = idCoruseLanguage;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public Integer getProgressbarCourseLanguage() {
		return this.progressbarCourseLanguage;
	}

	public void setProgressbarCourseLanguage(Integer progressbarCourseLanguage) {
		this.progressbarCourseLanguage = progressbarCourseLanguage;
	}

	public String getImgCourseLanguage() {
		return this.imgCourseLanguage;
	}

	public void setImgCourseLanguage(String imgCourseLanguage) {
		this.imgCourseLanguage = imgCourseLanguage;
	}

}
