package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private int idCourse;
	private Teacher teacher;
	private String nameCourse;
	private String passwordCourse;
	private Integer numberStudent;
	private Integer quantityLanguage;
	private Date startCourse;
	private Date endCourse;
	private Set<Student> students = new HashSet<Student>(0);
	private Set<CourseMission> courseMissions = new HashSet<CourseMission>(0);
	private Set<CourseLanguage> courseLanguages = new HashSet<CourseLanguage>(0);

	public Course() {
	}

	public Course(int idCourse) {
		this.idCourse = idCourse;
	}

	public Course(int idCourse, Teacher teacher, String nameCourse, String passwordCourse, Integer numberStudent,
			Integer quantityLanguage, Date startCourse, Date endCourse, Set<Student> students,
			Set<CourseMission> courseMissions, Set<CourseLanguage> courseLanguages) {
		this.idCourse = idCourse;
		this.teacher = teacher;
		this.nameCourse = nameCourse;
		this.passwordCourse = passwordCourse;
		this.numberStudent = numberStudent;
		this.quantityLanguage = quantityLanguage;
		this.startCourse = startCourse;
		this.endCourse = endCourse;
		this.students = students;
		this.courseMissions = courseMissions;
		this.courseLanguages = courseLanguages;
	}

	public int getIdCourse() {
		return this.idCourse;
	}

	public void setIdCourse(int idCourse) {
		this.idCourse = idCourse;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public String getNameCourse() {
		return this.nameCourse;
	}

	public void setNameCourse(String nameCourse) {
		this.nameCourse = nameCourse;
	}

	public String getPasswordCourse() {
		return this.passwordCourse;
	}

	public void setPasswordCourse(String passwordCourse) {
		this.passwordCourse = passwordCourse;
	}

	public Integer getNumberStudent() {
		return this.numberStudent;
	}

	public void setNumberStudent(Integer numberStudent) {
		this.numberStudent = numberStudent;
	}

	public Integer getQuantityLanguage() {
		return this.quantityLanguage;
	}

	public void setQuantityLanguage(Integer quantityLanguage) {
		this.quantityLanguage = quantityLanguage;
	}

	public Date getStartCourse() {
		return this.startCourse;
	}

	public void setStartCourse(Date startCourse) {
		this.startCourse = startCourse;
	}

	public Date getEndCourse() {
		return this.endCourse;
	}

	public void setEndCourse(Date endCourse) {
		this.endCourse = endCourse;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	public Set<CourseMission> getCourseMissions() {
		return this.courseMissions;
	}

	public void setCourseMissions(Set<CourseMission> courseMissions) {
		this.courseMissions = courseMissions;
	}

	public Set<CourseLanguage> getCourseLanguages() {
		return this.courseLanguages;
	}

	public void setCourseLanguages(Set<CourseLanguage> courseLanguages) {
		this.courseLanguages = courseLanguages;
	}

}
