package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

	private int idLanguage;
	private String nameLanguage;
	private Integer scoreParty;
	private Set<CourseLanguage> courseLanguages = new HashSet<CourseLanguage>(0);
	private Set<StudentLanguage> studentLanguages = new HashSet<StudentLanguage>(0);

	public Language() {
	}

	public Language(int idLanguage) {
		this.idLanguage = idLanguage;
	}

	public Language(int idLanguage, String nameLanguage, Integer scoreParty, Set<CourseLanguage> courseLanguages,
			Set<StudentLanguage> studentLanguages) {
		this.idLanguage = idLanguage;
		this.nameLanguage = nameLanguage;
		this.scoreParty = scoreParty;
		this.courseLanguages = courseLanguages;
		this.studentLanguages = studentLanguages;
	}

	public int getIdLanguage() {
		return this.idLanguage;
	}

	public void setIdLanguage(int idLanguage) {
		this.idLanguage = idLanguage;
	}

	public String getNameLanguage() {
		return this.nameLanguage;
	}

	public void setNameLanguage(String nameLanguage) {
		this.nameLanguage = nameLanguage;
	}

	public Integer getScoreParty() {
		return this.scoreParty;
	}

	public void setScoreParty(Integer scoreParty) {
		this.scoreParty = scoreParty;
	}

	public Set<CourseLanguage> getCourseLanguages() {
		return this.courseLanguages;
	}

	public void setCourseLanguages(Set<CourseLanguage> courseLanguages) {
		this.courseLanguages = courseLanguages;
	}

	public Set<StudentLanguage> getStudentLanguages() {
		return this.studentLanguages;
	}

	public void setStudentLanguages(Set<StudentLanguage> studentLanguages) {
		this.studentLanguages = studentLanguages;
	}

}
