package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mission generated by hbm2java
 */
public class Mission implements java.io.Serializable {

	private int idMission;
	private MissionLevel missionLevel;
	private MissionType missionType;
	private Recompense recompense;
	private String titleMission;
	private String descriptionMission;
	private Integer scoreMission;
	private Date dateLimit;
	private Character stateMission;
	private Character sendMission;
	private Set<CourseMission> courseMissions = new HashSet<CourseMission>(0);
	private Set<CourseMissionRolStudent> courseMissionRolStudents = new HashSet<CourseMissionRolStudent>(0);
	private Set<StudentMission> studentMissions = new HashSet<StudentMission>(0);

	public Mission() {
	}

	public Mission(int idMission) {
		this.idMission = idMission;
	}

	public Mission(int idMission, MissionLevel missionLevel, MissionType missionType, Recompense recompense,
			String titleMission, String descriptionMission, Integer scoreMission, Date dateLimit,
			Character stateMission, Character sendMission, Set<CourseMission> courseMissions,
			Set<CourseMissionRolStudent> courseMissionRolStudents, Set<StudentMission> studentMissions) {
		this.idMission = idMission;
		this.missionLevel = missionLevel;
		this.missionType = missionType;
		this.recompense = recompense;
		this.titleMission = titleMission;
		this.descriptionMission = descriptionMission;
		this.scoreMission = scoreMission;
		this.dateLimit = dateLimit;
		this.stateMission = stateMission;
		this.sendMission = sendMission;
		this.courseMissions = courseMissions;
		this.courseMissionRolStudents = courseMissionRolStudents;
		this.studentMissions = studentMissions;
	}

	public int getIdMission() {
		return this.idMission;
	}

	public void setIdMission(int idMission) {
		this.idMission = idMission;
	}

	public MissionLevel getMissionLevel() {
		return this.missionLevel;
	}

	public void setMissionLevel(MissionLevel missionLevel) {
		this.missionLevel = missionLevel;
	}

	public MissionType getMissionType() {
		return this.missionType;
	}

	public void setMissionType(MissionType missionType) {
		this.missionType = missionType;
	}

	public Recompense getRecompense() {
		return this.recompense;
	}

	public void setRecompense(Recompense recompense) {
		this.recompense = recompense;
	}

	public String getTitleMission() {
		return this.titleMission;
	}

	public void setTitleMission(String titleMission) {
		this.titleMission = titleMission;
	}

	public String getDescriptionMission() {
		return this.descriptionMission;
	}

	public void setDescriptionMission(String descriptionMission) {
		this.descriptionMission = descriptionMission;
	}

	public Integer getScoreMission() {
		return this.scoreMission;
	}

	public void setScoreMission(Integer scoreMission) {
		this.scoreMission = scoreMission;
	}

	public Date getDateLimit() {
		return this.dateLimit;
	}

	public void setDateLimit(Date dateLimit) {
		this.dateLimit = dateLimit;
	}

	public Character getStateMission() {
		return this.stateMission;
	}

	public void setStateMission(Character stateMission) {
		this.stateMission = stateMission;
	}

	public Character getSendMission() {
		return this.sendMission;
	}

	public void setSendMission(Character sendMission) {
		this.sendMission = sendMission;
	}

	public Set<CourseMission> getCourseMissions() {
		return this.courseMissions;
	}

	public void setCourseMissions(Set<CourseMission> courseMissions) {
		this.courseMissions = courseMissions;
	}

	public Set<CourseMissionRolStudent> getCourseMissionRolStudents() {
		return this.courseMissionRolStudents;
	}

	public void setCourseMissionRolStudents(Set<CourseMissionRolStudent> courseMissionRolStudents) {
		this.courseMissionRolStudents = courseMissionRolStudents;
	}

	public Set<StudentMission> getStudentMissions() {
		return this.studentMissions;
	}

	public void setStudentMissions(Set<StudentMission> studentMissions) {
		this.studentMissions = studentMissions;
	}

}
