package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * MissionLevel generated by hbm2java
 */
public class MissionLevel implements java.io.Serializable {

	private int idMissionLevel;
	private String nameMissionLevel;
	private String imgMissionLevel;
	private Integer scoreMissionLevel;
	private Set<Mission> missions = new HashSet<Mission>(0);

	public MissionLevel() {
	}

	public MissionLevel(int idMissionLevel) {
		this.idMissionLevel = idMissionLevel;
	}

	public MissionLevel(int idMissionLevel, String nameMissionLevel, String imgMissionLevel, Integer scoreMissionLevel,
			Set<Mission> missions) {
		this.idMissionLevel = idMissionLevel;
		this.nameMissionLevel = nameMissionLevel;
		this.imgMissionLevel = imgMissionLevel;
		this.scoreMissionLevel = scoreMissionLevel;
		this.missions = missions;
	}

	public int getIdMissionLevel() {
		return this.idMissionLevel;
	}

	public void setIdMissionLevel(int idMissionLevel) {
		this.idMissionLevel = idMissionLevel;
	}

	public String getNameMissionLevel() {
		return this.nameMissionLevel;
	}

	public void setNameMissionLevel(String nameMissionLevel) {
		this.nameMissionLevel = nameMissionLevel;
	}

	public String getImgMissionLevel() {
		return this.imgMissionLevel;
	}

	public void setImgMissionLevel(String imgMissionLevel) {
		this.imgMissionLevel = imgMissionLevel;
	}

	public Integer getScoreMissionLevel() {
		return this.scoreMissionLevel;
	}

	public void setScoreMissionLevel(Integer scoreMissionLevel) {
		this.scoreMissionLevel = scoreMissionLevel;
	}

	public Set<Mission> getMissions() {
		return this.missions;
	}

	public void setMissions(Set<Mission> missions) {
		this.missions = missions;
	}

}
