package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * MissionState generated by hbm2java
 */
public class MissionState implements java.io.Serializable {

	private int idMissionState;
	private String nameMissionState;
	private Set<CourseMissionStudent> courseMissionStudents = new HashSet<CourseMissionStudent>(0);

	public MissionState() {
	}

	public MissionState(int idMissionState) {
		this.idMissionState = idMissionState;
	}

	public MissionState(int idMissionState, String nameMissionState, Set<CourseMissionStudent> courseMissionStudents) {
		this.idMissionState = idMissionState;
		this.nameMissionState = nameMissionState;
		this.courseMissionStudents = courseMissionStudents;
	}

	public int getIdMissionState() {
		return this.idMissionState;
	}

	public void setIdMissionState(int idMissionState) {
		this.idMissionState = idMissionState;
	}

	public String getNameMissionState() {
		return this.nameMissionState;
	}

	public void setNameMissionState(String nameMissionState) {
		this.nameMissionState = nameMissionState;
	}

	public Set<CourseMissionStudent> getCourseMissionStudents() {
		return this.courseMissionStudents;
	}

	public void setCourseMissionStudents(Set<CourseMissionStudent> courseMissionStudents) {
		this.courseMissionStudents = courseMissionStudents;
	}

}
