package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * MissionType generated by hbm2java
 */
public class MissionType implements java.io.Serializable {

	private int idMissionType;
	private String descriptionMissionType;
	private Set<Mission> missions = new HashSet<Mission>(0);

	public MissionType() {
	}

	public MissionType(int idMissionType) {
		this.idMissionType = idMissionType;
	}

	public MissionType(int idMissionType, String descriptionMissionType, Set<Mission> missions) {
		this.idMissionType = idMissionType;
		this.descriptionMissionType = descriptionMissionType;
		this.missions = missions;
	}

	public int getIdMissionType() {
		return this.idMissionType;
	}

	public void setIdMissionType(int idMissionType) {
		this.idMissionType = idMissionType;
	}

	public String getDescriptionMissionType() {
		return this.descriptionMissionType;
	}

	public void setDescriptionMissionType(String descriptionMissionType) {
		this.descriptionMissionType = descriptionMissionType;
	}

	public Set<Mission> getMissions() {
		return this.missions;
	}

	public void setMissions(Set<Mission> missions) {
		this.missions = missions;
	}

}
