package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Note generated by hbm2java
 */
public class Note implements java.io.Serializable {

	private int idNote;
	private BigDecimal qualificationNote;
	private Set<CourseMission> courseMissions = new HashSet<CourseMission>(0);

	public Note() {
	}

	public Note(int idNote) {
		this.idNote = idNote;
	}

	public Note(int idNote, BigDecimal qualificationNote, Set<CourseMission> courseMissions) {
		this.idNote = idNote;
		this.qualificationNote = qualificationNote;
		this.courseMissions = courseMissions;
	}

	public int getIdNote() {
		return this.idNote;
	}

	public void setIdNote(int idNote) {
		this.idNote = idNote;
	}

	public BigDecimal getQualificationNote() {
		return this.qualificationNote;
	}

	public void setQualificationNote(BigDecimal qualificationNote) {
		this.qualificationNote = qualificationNote;
	}

	public Set<CourseMission> getCourseMissions() {
		return this.courseMissions;
	}

	public void setCourseMissions(Set<CourseMission> courseMissions) {
		this.courseMissions = courseMissions;
	}

}
