package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProgrammingLevel generated by hbm2java
 */
public class ProgrammingLevel implements java.io.Serializable {

	private int idProgrammingLevel;
	private String nameProgrammingLevel;
	private Set<StudentProgrammingLevel> studentProgrammingLevels = new HashSet<StudentProgrammingLevel>(0);

	public ProgrammingLevel() {
	}

	public ProgrammingLevel(int idProgrammingLevel) {
		this.idProgrammingLevel = idProgrammingLevel;
	}

	public ProgrammingLevel(int idProgrammingLevel, String nameProgrammingLevel,
			Set<StudentProgrammingLevel> studentProgrammingLevels) {
		this.idProgrammingLevel = idProgrammingLevel;
		this.nameProgrammingLevel = nameProgrammingLevel;
		this.studentProgrammingLevels = studentProgrammingLevels;
	}

	public int getIdProgrammingLevel() {
		return this.idProgrammingLevel;
	}

	public void setIdProgrammingLevel(int idProgrammingLevel) {
		this.idProgrammingLevel = idProgrammingLevel;
	}

	public String getNameProgrammingLevel() {
		return this.nameProgrammingLevel;
	}

	public void setNameProgrammingLevel(String nameProgrammingLevel) {
		this.nameProgrammingLevel = nameProgrammingLevel;
	}

	public Set<StudentProgrammingLevel> getStudentProgrammingLevels() {
		return this.studentProgrammingLevels;
	}

	public void setStudentProgrammingLevels(Set<StudentProgrammingLevel> studentProgrammingLevels) {
		this.studentProgrammingLevels = studentProgrammingLevels;
	}

}
