package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

/**
 * RecompenseStudent generated by hbm2java
 */
public class RecompenseStudent implements java.io.Serializable {

	private int idRecompenseStudent;
	private Recompense recompense;
	private Student student;

	public RecompenseStudent() {
	}

	public RecompenseStudent(int idRecompenseStudent) {
		this.idRecompenseStudent = idRecompenseStudent;
	}

	public RecompenseStudent(int idRecompenseStudent, Recompense recompense, Student student) {
		this.idRecompenseStudent = idRecompenseStudent;
		this.recompense = recompense;
		this.student = student;
	}

	public int getIdRecompenseStudent() {
		return this.idRecompenseStudent;
	}

	public void setIdRecompenseStudent(int idRecompenseStudent) {
		this.idRecompenseStudent = idRecompenseStudent;
	}

	public Recompense getRecompense() {
		return this.recompense;
	}

	public void setRecompense(Recompense recompense) {
		this.recompense = recompense;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}
