package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * RolStudent generated by hbm2java
 */
public class RolStudent implements java.io.Serializable {

	private int idRolStudent;
	private Rol rol;
	private Student student;
	private Set<CourseMissionRolStudent> courseMissionRolStudents = new HashSet<CourseMissionRolStudent>(0);

	public RolStudent() {
	}

	public RolStudent(int idRolStudent) {
		this.idRolStudent = idRolStudent;
	}

	public RolStudent(int idRolStudent, Rol rol, Student student,
			Set<CourseMissionRolStudent> courseMissionRolStudents) {
		this.idRolStudent = idRolStudent;
		this.rol = rol;
		this.student = student;
		this.courseMissionRolStudents = courseMissionRolStudents;
	}

	public int getIdRolStudent() {
		return this.idRolStudent;
	}

	public void setIdRolStudent(int idRolStudent) {
		this.idRolStudent = idRolStudent;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Set<CourseMissionRolStudent> getCourseMissionRolStudents() {
		return this.courseMissionRolStudents;
	}

	public void setCourseMissionRolStudents(Set<CourseMissionRolStudent> courseMissionRolStudents) {
		this.courseMissionRolStudents = courseMissionRolStudents;
	}

}
