package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

/**
 * StudentMission generated by hbm2java
 */
public class StudentMission implements java.io.Serializable {

	private int idStudentMission;
	private Mission mission;
	private Student student;

	public StudentMission() {
	}

	public StudentMission(int idStudentMission) {
		this.idStudentMission = idStudentMission;
	}

	public StudentMission(int idStudentMission, Mission mission, Student student) {
		this.idStudentMission = idStudentMission;
		this.mission = mission;
		this.student = student;
	}

	public int getIdStudentMission() {
		return this.idStudentMission;
	}

	public void setIdStudentMission(int idStudentMission) {
		this.idStudentMission = idStudentMission;
	}

	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}
