package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

/**
 * StudentLanguage generated by hbm2java
 */
public class StudentLanguage implements java.io.Serializable {

	private int idStudentLanguage;
	private Language language;
	private Student student;

	public StudentLanguage() {
	}

	public StudentLanguage(int idStudentLanguage) {
		this.idStudentLanguage = idStudentLanguage;
	}

	public StudentLanguage(int idStudentLanguage, Language language, Student student) {
		this.idStudentLanguage = idStudentLanguage;
		this.language = language;
		this.student = student;
	}

	public int getIdStudentLanguage() {
		return this.idStudentLanguage;
	}

	public void setIdStudentLanguage(int idStudentLanguage) {
		this.idStudentLanguage = idStudentLanguage;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

}
