package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int idStudent;
	private Avatar avatar;
	private Course course;
	private String nameStudent;
	private String lastnameStudent;
	private Character genderStudent;
	private String nicknameStudent;
	private String emailStudent;
	private String passwordStudent;
	private Integer scoreStudent;
	private Character semestreStudent;
	private Date birthdateStudent;
	private Set<CourseMissionStudent> courseMissionStudents = new HashSet<CourseMissionStudent>(0);
	private Set<RecompenseStudent> recompenseStudents = new HashSet<RecompenseStudent>(0);
	private Set<RolStudent> rolStudents = new HashSet<RolStudent>(0);
	private Set<StudentLanguage> studentLanguages = new HashSet<StudentLanguage>(0);
	private Set<StudentMission> studentMissions = new HashSet<StudentMission>(0);
	private Set<StudentProgrammingLevel> studentProgrammingLevels = new HashSet<StudentProgrammingLevel>(0);

	public Student() {
	}

	public Student(int idStudent) {
		this.idStudent = idStudent;
	}

	public Student(int idStudent, Avatar avatar, Course course, String nameStudent, String lastnameStudent,
			Character genderStudent, String nicknameStudent, String emailStudent, String passwordStudent,
			Integer scoreStudent, Character semestreStudent, Date birthdateStudent,
			Set<CourseMissionStudent> courseMissionStudents, Set<RecompenseStudent> recompenseStudents,
			Set<RolStudent> rolStudents, Set<StudentLanguage> studentLanguages, Set<StudentMission> studentMissions,
			Set<StudentProgrammingLevel> studentProgrammingLevels) {
		this.idStudent = idStudent;
		this.avatar = avatar;
		this.course = course;
		this.nameStudent = nameStudent;
		this.lastnameStudent = lastnameStudent;
		this.genderStudent = genderStudent;
		this.nicknameStudent = nicknameStudent;
		this.emailStudent = emailStudent;
		this.passwordStudent = passwordStudent;
		this.scoreStudent = scoreStudent;
		this.semestreStudent = semestreStudent;
		this.birthdateStudent = birthdateStudent;
		this.courseMissionStudents = courseMissionStudents;
		this.recompenseStudents = recompenseStudents;
		this.rolStudents = rolStudents;
		this.studentLanguages = studentLanguages;
		this.studentMissions = studentMissions;
		this.studentProgrammingLevels = studentProgrammingLevels;
	}

	public int getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(int idStudent) {
		this.idStudent = idStudent;
	}

	public Avatar getAvatar() {
		return this.avatar;
	}

	public void setAvatar(Avatar avatar) {
		this.avatar = avatar;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getNameStudent() {
		return this.nameStudent;
	}

	public void setNameStudent(String nameStudent) {
		this.nameStudent = nameStudent;
	}

	public String getLastnameStudent() {
		return this.lastnameStudent;
	}

	public void setLastnameStudent(String lastnameStudent) {
		this.lastnameStudent = lastnameStudent;
	}

	public Character getGenderStudent() {
		return this.genderStudent;
	}

	public void setGenderStudent(Character genderStudent) {
		this.genderStudent = genderStudent;
	}

	public String getNicknameStudent() {
		return this.nicknameStudent;
	}

	public void setNicknameStudent(String nicknameStudent) {
		this.nicknameStudent = nicknameStudent;
	}

	public String getEmailStudent() {
		return this.emailStudent;
	}

	public void setEmailStudent(String emailStudent) {
		this.emailStudent = emailStudent;
	}

	public String getPasswordStudent() {
		return this.passwordStudent;
	}

	public void setPasswordStudent(String passwordStudent) {
		this.passwordStudent = passwordStudent;
	}

	public Integer getScoreStudent() {
		return this.scoreStudent;
	}

	public void setScoreStudent(Integer scoreStudent) {
		this.scoreStudent = scoreStudent;
	}

	public Character getSemestreStudent() {
		return this.semestreStudent;
	}

	public void setSemestreStudent(Character semestreStudent) {
		this.semestreStudent = semestreStudent;
	}

	public Date getBirthdateStudent() {
		return this.birthdateStudent;
	}

	public void setBirthdateStudent(Date birthdateStudent) {
		this.birthdateStudent = birthdateStudent;
	}

	public Set<CourseMissionStudent> getCourseMissionStudents() {
		return this.courseMissionStudents;
	}

	public void setCourseMissionStudents(Set<CourseMissionStudent> courseMissionStudents) {
		this.courseMissionStudents = courseMissionStudents;
	}

	public Set<RecompenseStudent> getRecompenseStudents() {
		return this.recompenseStudents;
	}

	public void setRecompenseStudents(Set<RecompenseStudent> recompenseStudents) {
		this.recompenseStudents = recompenseStudents;
	}

	public Set<RolStudent> getRolStudents() {
		return this.rolStudents;
	}

	public void setRolStudents(Set<RolStudent> rolStudents) {
		this.rolStudents = rolStudents;
	}

	public Set<StudentLanguage> getStudentLanguages() {
		return this.studentLanguages;
	}

	public void setStudentLanguages(Set<StudentLanguage> studentLanguages) {
		this.studentLanguages = studentLanguages;
	}

	public Set<StudentMission> getStudentMissions() {
		return this.studentMissions;
	}

	public void setStudentMissions(Set<StudentMission> studentMissions) {
		this.studentMissions = studentMissions;
	}

	public Set<StudentProgrammingLevel> getStudentProgrammingLevels() {
		return this.studentProgrammingLevels;
	}

	public void setStudentProgrammingLevels(Set<StudentProgrammingLevel> studentProgrammingLevels) {
		this.studentProgrammingLevels = studentProgrammingLevels;
	}

}
