package co.edu.usbcali.backend.modelo;
// Generated 13/06/2018 04:59:00 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private int idTeacher;
	private String username;
	private String nameUser;
	private String lastnameUser;
	private String emailUser;
	private String passwordUser;
	private String imageUser;
	private Date birthdateUser;
	private Character genderUser;
	private Set<Course> courses = new HashSet<Course>(0);

	public Teacher() {
	}

	public Teacher(int idTeacher) {
		this.idTeacher = idTeacher;
	}

	public Teacher(int idTeacher, String username, String nameUser, String lastnameUser, String emailUser,
			String passwordUser, String imageUser, Date birthdateUser, Character genderUser, Set<Course> courses) {
		this.idTeacher = idTeacher;
		this.username = username;
		this.nameUser = nameUser;
		this.lastnameUser = lastnameUser;
		this.emailUser = emailUser;
		this.passwordUser = passwordUser;
		this.imageUser = imageUser;
		this.birthdateUser = birthdateUser;
		this.genderUser = genderUser;
		this.courses = courses;
	}

	public int getIdTeacher() {
		return this.idTeacher;
	}

	public void setIdTeacher(int idTeacher) {
		this.idTeacher = idTeacher;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getNameUser() {
		return this.nameUser;
	}

	public void setNameUser(String nameUser) {
		this.nameUser = nameUser;
	}

	public String getLastnameUser() {
		return this.lastnameUser;
	}

	public void setLastnameUser(String lastnameUser) {
		this.lastnameUser = lastnameUser;
	}

	public String getEmailUser() {
		return this.emailUser;
	}

	public void setEmailUser(String emailUser) {
		this.emailUser = emailUser;
	}

	public String getPasswordUser() {
		return this.passwordUser;
	}

	public void setPasswordUser(String passwordUser) {
		this.passwordUser = passwordUser;
	}

	public String getImageUser() {
		return this.imageUser;
	}

	public void setImageUser(String imageUser) {
		this.imageUser = imageUser;
	}

	public Date getBirthdateUser() {
		return this.birthdateUser;
	}

	public void setBirthdateUser(Date birthdateUser) {
		this.birthdateUser = birthdateUser;
	}

	public Character getGenderUser() {
		return this.genderUser;
	}

	public void setGenderUser(Character genderUser) {
		this.genderUser = genderUser;
	}

	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

}
